services:
  db:
    image: postgres:15-alpine
    container_name: p2p_db
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: "Europe/Moscow"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: p2p_redis
    restart: always

  bot:
    build: .
    container_name: p2p_bot
    restart: unless-stopped
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow

volumes:
  postgres_data: