"""add dispute table

Revision ID: e0390f838e28
Revises: f6b053374986
Create Date: 2026-05-31 23:25:31.946977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0390f838e28'
down_revision: Union[str, None] = 'f6b053374986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_id', sa.BigInteger(), nullable=False),
    sa.Column('group_topic_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_disputes_deal_id_deals')),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], name=op.f('fk_disputes_opened_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disputes')),
    sa.UniqueConstraint('deal_id', name=op.f('uq_disputes_deal_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    # ### end Alembic commands ###
