"""inital DB

Revision ID: f6b053374986
Revises: 
Create Date: 2026-05-31 21:13:05.977205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b053374986'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('deal_count', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('conflict_strikes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('display_name', name=op.f('uq_users_display_name'))
    )
    op.create_table('user_requisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_requisites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_requisites'))
    )
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('requisite_id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.Enum('RUB', 'KRW', 'KZT', name='currency'), nullable=False),
    sa.Column('quote_currency', sa.Enum('RUB', 'KRW', 'KZT', name='currency'), nullable=False),
    sa.Column('min_limit', sa.Float(), nullable=False),
    sa.Column('max_limit', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('bank', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'HIDDEN', 'ARCHIVED', name='adstatus'), nullable=False),
    sa.ForeignKeyConstraint(['requisite_id'], ['user_requisites.id'], name=op.f('fk_advertisements_requisite_id_user_requisites'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_advertisements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisements'))
    )
    op.create_index(op.f('ix_advertisements_public_id'), 'advertisements', ['public_id'], unique=True)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=10), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.BigInteger(), nullable=False),
    sa.Column('seller_id', sa.BigInteger(), nullable=False),
    sa.Column('requisite_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_BUYER_PAY', 'WAITING_SELLER_CONFIRM', 'WAITING_SELLER_PAY', 'WAITING_BUYER_CONFIRM', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='dealstatus'), nullable=False),
    sa.Column('amount_base', sa.Float(), nullable=False),
    sa.Column('amount_quote', sa.Float(), nullable=False),
    sa.Column('buyer_receipt_id', sa.String(length=255), nullable=True),
    sa.Column('seller_receipt_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['advertisements.id'], name=op.f('fk_deals_ad_id_advertisements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_deals_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisite_id'], ['user_requisites.id'], name=op.f('fk_deals_requisite_id_user_requisites'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_deals_seller_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_public_id'), 'deals', ['public_id'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=False),
    sa.Column('to_user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_reviews_deal_id_deals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_reviews_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_reviews_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index(op.f('ix_deals_public_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_advertisements_public_id'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_table('user_requisites')
    op.drop_table('users')
    # ### end Alembic commands ###
